## Binary Genetic Algorithm 

In [1]:
from BGA import BGA
import numpy as np 

In [2]:
def values(arr):
    w= [1, 2, 4 ,8 ,-16] 
    out = np.sum(w * arr)
    return out



In [3]:
model = BGA(max_iteratoin=30, n_population=6, num_param=5, score_func=values, prob_crossover=.5, prob_mut=.5, crossover_method='uniform')


In [4]:
model.fit()

num population 6
current_best_score 14
current_best_person [0 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_best_person [1 1 1 1 0]
_______________________________________________
num population 6
current_best_score 15
current_b

In [5]:
model.print_pop()

last population  [[1 1 1 1 0]
 [1 0 1 1 0]
 [1 1 0 1 0]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 0 1 1 0]]
best result  [1 1 1 1 0]


## NQueen Genetic Algorithm 

In [6]:
from Nqueen import Nqueens

In [13]:
model = Nqueens(n_queens=20 , n_population= 150, max_iteration= 150, crossover_method='single', prob_mut= 0.5, prob_crossover= .5)

In [14]:
model.fit()

num population 150
current_best_score 388
current_best_person [11. 14.  3.  9.  6. 10. 18.  5.  0.  8. 17.  7. 16.  2.  4. 15. 19. 12.
 13.  1.]
_______________________________________________
num population 150
current_best_score 388
current_best_person [11. 14.  3.  9.  6. 10. 18.  5.  0.  8. 17.  7. 16.  2.  4. 15. 19. 12.
 13.  1.]
_______________________________________________
num population 150
current_best_score 388
current_best_person [11. 14.  3.  9.  6. 10. 18.  5.  0.  8. 17.  7. 16.  2.  4. 15. 19. 12.
 13.  1.]
_______________________________________________
num population 150
current_best_score 388
current_best_person [11. 14.  3.  9.  6. 10. 18.  5.  0.  8. 17.  7. 16.  2.  4. 15. 19. 12.
 13.  1.]
_______________________________________________
num population 150
current_best_score 388
current_best_person [11. 14.  3.  9.  6. 10. 18.  5.  0.  8. 17.  7. 16.  2.  4. 15. 19. 12.
 13.  1.]
_______________________________________________
num population 150
current_best_sco